## queue dengan array

In [ ]:
import numpy as np

In [ ]:
class ArrayLinQueue:
    def __init__(self, dtype, array_max):
        self.dtype = dtype
        self.array_max = array_max
        self.array = np.empty(array_max, dtype = dtype)
        self.front = -1
        self.rear = -1

    def get_size(self):
        size = (self.rear - self.front) + 1
        return size

    def get_capacity_queue(self):
        if self.front == -1:
            capacity_queue = self.array_max
        else:
            capacity_queue = self.array_max - self.front
        return capacity_queue

    def is_empty(self):
        if self.front == -1:
            return True
        else:
            return False

    def is_full(self):
        if self.rear == self.array_max -1:
            return True
        else:
            return False

    def enqueue(self, newdata):
        if self.is_full():
            print("Error enqueue: queue sudah penuh sebelumnya")
        elif self.front == -1:
            self.front += 1
            self.rear += 1
            self.array[self.rear] = newdata
        else:
            self.rear += 1
            self.array[self.rear] = newdata

    def peek(self):
        if self.is_empty():
            print("Error peek: queue sedang kosong")
        else:
            return self.array[self.front]

    def dequeue(self):
        if self.is_empty():
            print("error dequeue: queue sedah kosong sebelumnya")
            return None
        elif (self.get_size() == 1):
            output = self.array[self.front]
            self.front = -1
            self.rear = -1
            return output
        else:
            output = self.array[self.front]
            self.front += 1
            return output

    def print_storage(self):
        print(self.array)

    def print_queue(self):
        print("front: ", end="")
        if self.is_empty():
            print("(tidak ada data): rear")
        else:
            for i in range(self.front, self.rear):
                print(self.array[i], end=" | ")
            print(self.array[self.rear], end ="")
            print(" : rear")

In [ ]:
arraylinqueue = ArrayLinQueue(int, 5)

In [ ]:
arraylinqueue.print_queue()

front: (tidak ada data): rear


In [ ]:
arraylinqueue.print_storage()

[     94569718872315                   0 8386019333807480933
 7022364301954937888                 176]


In [ ]:
arraylinqueue.enqueue(-18)
arraylinqueue.enqueue(67)
arraylinqueue.enqueue(32)

In [ ]:
arraylinqueue.print_queue()

front: -18 | 67 | 32 : rear


In [ ]:
arraylinqueue.print_storage()

[                -18                  67                  32
 7022364301954937888                 176]


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
2


In [ ]:
arraylinqueue.enqueue(-29)

In [ ]:
arraylinqueue.print_queue()

front: -18 | 67 | 32 | -29 : rear


In [ ]:
arraylinqueue.print_storage()

[-18  67  32 -29 176]


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
3


In [ ]:
print(arraylinqueue.peek())

-18


In [ ]:
arraylinqueue.print_queue()

front: -18 | 67 | 32 | -29 : rear


In [ ]:
nilai = arraylinqueue.dequeue()
print(nilai)

-18


In [ ]:
arraylinqueue.print_queue()

front: 67 | 32 | -29 : rear


In [ ]:
arraylinqueue.print_storage()

[-18  67  32 -29 176]


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

1
3


In [ ]:
print(arraylinqueue.dequeue())

67


In [ ]:
arraylinqueue.print_queue()

front: 32 | -29 : rear


In [ ]:
print(arraylinqueue.dequeue())
print(arraylinqueue.dequeue())

32
-29


In [ ]:
arraylinqueue.print_queue()

front: (tidak ada data): rear


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

-1
-1


In [ ]:
print(arraylinqueue.dequeue())

error dequeue: queue sedah kosong sebelumnya
None


In [ ]:
arraylinqueue.enqueue(-25)
arraylinqueue.enqueue(13)
arraylinqueue.enqueue(48)
arraylinqueue.enqueue(-87)
arraylinqueue.enqueue(38)

In [ ]:
arraylinqueue.print_queue()

front: -25 | 13 | 48 | -87 | 38 : rear


In [ ]:
arraylinqueue.print_storage()

[-25  13  48 -87  38]


In [ ]:
print(arraylinqueue.is_full())

True


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

0
4


In [ ]:
arraylinqueue.enqueue(24)

Error enqueue: queue sudah penuh sebelumnya


In [ ]:
print(arraylinqueue.dequeue())
print(arraylinqueue.dequeue())

-25
13


In [ ]:
arraylinqueue.print_queue()

front: 48 | -87 | 38 : rear


In [ ]:
arraylinqueue.print_storage()

[-25  13  48 -87  38]


In [ ]:
print(arraylinqueue.front)
print(arraylinqueue.rear)

2
4


In [ ]:
arraylinqueue.enqueue(-53)

Error enqueue: queue sudah penuh sebelumnya


## circular queue dengan array

In [ ]:
class ArrayCircQueue:
    def __init__(self, dtype, max):
        self.dtype = dtype
        self.max = max
        self.array = np.empty(max, dtype = dtype)
        self.front = -1
        self.rear = -1

    def is_empty(self):
        if self.front == -1:
            return True
        else:
            return False

    def is_full(self):
        if self.front == (self.rear + 1) % self.max:
            return True
        else:
            return False

    def get_size(self):
        if self.is_empty():
            size = 0
        elif self.front <= self.rear:
            size = (self.rear - self.front) + 1
        else:
            size = self.max - (self.front - self.rear - 1)
        return size

    def get_capacity(self):
        return self.max

    def enqueue(self, newdata):
        if self.is_full():
            print("error enqueue: queue sudah penuh sebelumnya")
        elif self.front == -1:
            self.front += 1
            self.rear += 1
            self.array[self.rear] = newdata
        else:
            self.rear = (self.rear + 1) % self.max
            self.array[self.rear] = newdata

    def peek(self):
        if self.is_empty():
            print("error peek: queue sudah kosong")
        else:
            return self.array[self.front]

    def dequeue(self):
        if self.is_empty():
            print("error dequeue = queue sudah kosong sebelumnya")
            return None
        elif (self.get_size() == 1):
            output = self.array[self.front]
            self.front = -1
            self.rear = -1
            return output
        else:
            output = self.array[self.front]
            self.front = (self.front + 1) % self.max
            return output

    def print_storage(self):
        print(self.array)

    def print_queue(self):
        print("front : ", end ="")
        if self.is_empty():
            print("(tidak ada data ): rear")
        else:
            i = self.front
            while i != self.rear:
                print(self.array[i], end=" | ")
                i = (i + 1) % self.max
            print(self.array[self.rear], end="")
            print(" : rear")

In [ ]:
arraycircqueue = ArrayCircQueue(int, 5)
arraycircqueue.print_queue()

front : (tidak ada data ): rear


In [ ]:
arraycircqueue.print_storage()

[                -18                  67                  32
                 -29 4607182418800017408]


In [ ]:
arraycircqueue.enqueue(65)
arraycircqueue.enqueue(-11)
arraycircqueue.enqueue(43)

In [ ]:
arraycircqueue.print_queue()

front : 65 | -11 | 43 : rear


In [ ]:
arraycircqueue.print_storage()

[                 65                 -11                  43
                 -29 4607182418800017408]


In [ ]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
2


In [ ]:
arraycircqueue.enqueue(97)
arraycircqueue.enqueue(-12)

In [ ]:
arraycircqueue.print_queue()

front : 65 | -11 | 43 | 97 | -12 : rear


In [ ]:
arraycircqueue.enqueue(46)

error enqueue: queue sudah penuh sebelumnya


In [ ]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [ ]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

0
4


In [ ]:
print(arraycircqueue.peek())

65


In [ ]:
print(arraycircqueue.dequeue())

65


In [ ]:
arraycircqueue.print_queue()

front : -11 | 43 | 97 | -12 : rear


In [ ]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [ ]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

1
4


In [ ]:
print(arraycircqueue.dequeue())
print(arraycircqueue.dequeue())

-11
43


In [ ]:
arraycircqueue.print_queue()

front : 97 | -12 : rear


In [ ]:
arraycircqueue.print_storage()

[ 65 -11  43  97 -12]


In [ ]:
arraycircqueue.enqueue(-74)

In [ ]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 : rear


In [ ]:
arraycircqueue.print_storage()

[-74 -11  43  97 -12]


In [ ]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
0


In [ ]:
arraycircqueue.enqueue(19)

In [ ]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 | 19 : rear


In [ ]:
arraycircqueue.print_storage()

[-74  19  43  97 -12]


In [ ]:
print(arraycircqueue.front)
print(arraycircqueue.rear)

3
1


In [ ]:
arraycircqueue.enqueue(85)

In [ ]:
arraycircqueue.print_queue()

front : 97 | -12 | -74 | 19 | 85 : rear


In [ ]:
arraycircqueue.print_storage()

[-74  19  85  97 -12]


In [ ]:
arraycircqueue.enqueue(-31)

error enqueue: queue sudah penuh sebelumnya


## linear queue dengan linked list

In [ ]:
class SLNode:
    def __init__(self, data, next = None):
        self.data = data
        self.next = next

In [ ]:
class SLLinQueue:
    def __init__(self):
        self.front = None
        self.rear = None

    def is_empty(self):
        if self.front == None:
            return True
        else:
            return False

    def get_size(self):
        size = 0
        temp = self.front
        while (temp!=None):
            size += 1
            temp = temp.next
        return size

    def enqueue(self, newdata):
        newnode = SLNode(newdata)
        if self.is_empty():
            self.front = newnode
            self.rear = newnode
        else:
            self.rear.next = newnode
            self.rear = newnode
    def peek(self):
        if self.is_empty():
            print("error peek: queue sedang kosong")
            return None
        else:
            return self.front.data

    def dequeue(self):
        if self.is_empty():
            print("error dequeue: queue sudah kosong sebelumnya")
            return None
        else:
            output = self.front.data
            temp = self.front
            self.front = self.front.next
            del temp
            return output

    def print_queue(self):
        print("front : ", end="")
        if self.is_empty():
            print("(tidak ada data) : rear")
        else:
            temp = self.front
            while temp != None:
                if temp.next != None:
                    print(temp.data, end = " | ")
                else:
                    print(temp.data, end = "")
                temp = temp.next
            print(" : rear")

    def print_storage(self):
        print ("front ->", end ="")
        if self.is_empty():
            print(" None <- rear")
        else:
            temp = self.front
            while temp != None:
                if temp.next != None:
                    print(temp.data, end = " - > ")
                else:
                    print(temp.data, end = " < - ")
                temp = temp.next
            print("rear")

In [ ]:
sllinqueue = SLLinQueue()
sllinqueue.print_queue()
sllinqueue.print_storage()

front : (tidak ada data) : rear
front -> None <- rear


In [ ]:
sllinqueue.enqueue(10)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 : rear
front ->10 < - rear


In [ ]:
sllinqueue.enqueue(46)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 46 : rear
front ->10 - > 46 < - rear


In [ ]:
sllinqueue.enqueue(-43)
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 46 | -43 : rear
front ->10 - > 46 - > -43 < - rear


In [ ]:
print(sllinqueue.peek())

10


In [ ]:
sllinqueue.print_queue()
sllinqueue.print_storage()

front : 10 | 46 | -43 : rear
front ->10 - > 46 - > -43 < - rear


In [ ]:
print(sllinqueue.dequeue())

10


In [ ]:
sllinqueue.print_queue()

front : 46 | -43 : rear


In [ ]:
sllinqueue.print_storage()

front ->46 - > -43 < - rear
